# Generated by Django 5.2.7 on 2025-11-09 21:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('duration_weeks', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Продолжительность (недели)')),
                ('difficulty_level', models.CharField(choices=[('beginnger', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginnger', max_length=20, verbose_name='Уровень сложности')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('complexity_level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Уровень сложности (1-5)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'courses',
                'ordering': ['complexity_level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название урока')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('lesson_type', models.CharField(choices=[('lecture', 'Лекция'), ('seminar', 'Семинар'), ('practice', 'Практика'), ('consultation', 'Консультация'), ('test', 'Зачет')], default='lecture', max_length=20, verbose_name='Тип урока')),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длительность (минуты)')),
                ('lesson_order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядковый номер')),
                ('has_homework', models.BooleanField(default=False, verbose_name='Есть домашнее задание')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('max_score', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Максимальный балл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'db_table': 'lessons',
                'ordering': ['module', 'lesson_order'],
            },
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('reviewer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('hire_date', models.DateField(verbose_name='Дата найма')),
                ('specialization', models.CharField(max_length=255, verbose_name='Специализация')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('suspended', 'Приостановлен'), ('graduated', 'Выпускник')], default='active', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Ревьюер',
                'verbose_name_plural': 'Ревьюеры',
                'db_table': 'reviewers',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('suspended', 'Приостановлен'), ('graduated', 'Выпускник')], default='active', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата зачисления')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('paused', 'Приостановлено'), ('waiting_payment', 'Ожидает оплаты')], default='active', max_length=20, verbose_name='Статус')),
                ('overall_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Общий балл')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Education.course', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Education.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Зачисление',
                'verbose_name_plural': 'Зачисления',
                'db_table': 'enrollments',
                'ordering': ['-enrollment_date'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('deadline_id', models.AutoField(primary_key=True, serialize=False)),
                ('deadline_type', models.CharField(choices=[('course_start', 'Начало курса'), ('course_completion', 'Завершение курса'), ('module_completion', 'Завершение модуля'), ('lesson_completion', 'Завершение урока'), ('homework_submission', 'Сдача домашнего задания')], max_length=20, verbose_name='Тип дедлайна')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID цели')),
                ('deadline_date', models.DateTimeField(verbose_name='Дата дедлайна')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('missed', 'Просрочено'), ('completed', 'Выполнено'), ('extended', 'Продлено'), ('cancelled', 'Отменено')], default='active', max_length=20, verbose_name='Статус')),
                ('urgency', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('critical', 'Критический')], default='normal', max_length=20, verbose_name='Срочность')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='Education.enrollment', verbose_name='Зачисление')),
            ],
            options={
                'verbose_name': 'Дедлайн',
                'verbose_name_plural': 'Дедлайны',
                'db_table': 'deadlines',
                'ordering': ['deadline_date'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на сертификат')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания действия')),
                ('verification_code', models.CharField(max_length=100, unique=True, verbose_name='Код проверки')),
                ('grade_level', models.CharField(blank=True, choices=[('beginnger', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], max_length=20, null=True, verbose_name='Уровень оценки')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='Education.enrollment', verbose_name='Зачисление')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'db_table': 'certificates',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('homework_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('max_score', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Максимальный балл')),
                ('deadline_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Дней на выполнение')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Опциональное')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='Education.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'db_table': 'homeworks',
                'ordering': ['lesson', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название модуля')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('module_order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядковый номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='Education.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'db_table': 'modules',
                'ordering': ['course', 'module_order'],
                'unique_together': {('course', 'module_order')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='Education.module', verbose_name='Модуль'),
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_text', models.TextField(verbose_name='Текст решения')),
                ('attachment_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на вложение')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('personal_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Персональный дедлайн')),
                ('score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Балл')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Обратная связь')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('status', models.CharField(choices=[('submitted', 'Отправлено'), ('under_review', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('needs_revision', 'Требует доработки'), ('resubmitted', 'Переотправлено')], default='submitted', max_length=20, verbose_name='Статус')),
                ('urgency', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('critical', 'Критический')], default='normal', max_length=20, verbose_name='Срочность')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='Education.enrollment', verbose_name='Зачисление')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Education.homework', verbose_name='Домашнее задание')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework_submissions', to='Education.reviewer', verbose_name='Проверяющий')),
            ],
            options={
                'verbose_name': 'Отправленное задание',
                'verbose_name_plural': 'Отправленные задания',
                'db_table': 'homework_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('prerequisite_id', models.AutoField(primary_key=True, serialize=False)),
                ('min_score', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Минимальный балл')),
                ('requirement_type', models.CharField(choices=[('mandatory', 'Обязательно'), ('recommended', 'Рекомендуется'), ('optional', 'Опционально')], default='mandatory', max_length=20, verbose_name='Тип требования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='Education.course', verbose_name='Курс')),
                ('required_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for_courses', to='Education.course', verbose_name='Требуемый курс')),
            ],
            options={
                'verbose_name': 'Предварительное требование',
                'verbose_name_plural': 'Предварительные требования',
                'db_table': 'course_prerequisites',
                'unique_together': {('course', 'required_course')},
            },
        ),
        migrations.CreateModel(
            name='LessonCompletion',
            fields=[
                ('completion_id', models.AutoField(primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершения')),
                ('score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Балл')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_completions', to='Education.enrollment', verbose_name='Зачисление')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='Education.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Завершение урока',
                'verbose_name_plural': 'Завершения уроков',
                'db_table': 'lesson_completions',
                'ordering': ['-completed_at'],
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'lesson_order')},
        ),
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('teacher_course_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_main_teacher', models.BooleanField(default=False, verbose_name='Основной преподаватель')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_courses', to='Education.course', verbose_name='Курс')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_courses', to='Education.reviewer', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Курс преподавателя',
                'verbose_name_plural': 'Курсы преподавателей',
                'db_table': 'teacher_courses',
                'unique_together': {('reviewer', 'course')},
            },
        ),
    ]
