# Generated by Django 5.2.7 on 2025-11-12 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-имя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание тега')),
                ('color', models.CharField(default='#6c757d', help_text='Цвет в формате HEX (#FF5733)', max_length=7, verbose_name='Цвет тега')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='certificate',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], max_length=20, null=True, verbose_name='Уровень оценки'),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20, verbose_name='Уровень сложности'),
        ),
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('coursetag_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_tags', to='Education.course', verbose_name='Курс')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_courses', to='Education.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег курса',
                'verbose_name_plural': 'Теги курсов',
                'db_table': 'course_tags',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='courses', through='Education.CourseTag', through_fields=('course', 'tag'), to='Education.tag', verbose_name='Теги'),
        ),
    ]
