# Generated by Django 5.2.7 on 2025-11-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0002_tag_alter_certificate_grade_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, default='#6c757d', help_text='Цвет в формате HEX (#FF5733)', max_length=50, unique=True, verbose_name='Цвет тега'),
        ),
    ]
