# Generated by Django 5.2.7 on 2025-11-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0003_alter_tag_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-is_featured', '-course_count', 'name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='reviewer',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрен администратором'),
        ),
        migrations.AddField(
            model_name='tag',
            name='course_count',
            field=models.IntegerField(default=0, verbose_name='Количество курсов'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Популярный тег'),
        ),
    ]
