# Generated by Django 5.2.7 on 2025-11-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0004_alter_tag_options_reviewer_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworksubmission',
            name='personal_deadline',
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(default='', verbose_name='Видео URL'),
        ),
    ]
