# Generated by Django 5.2.7 on 2025-12-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0005_remove_homeworksubmission_personal_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
