# Generated by Django 5.2.7 on 2025-12-17 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0006_alter_tag_tag_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(default=True, null=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, default='', verbose_name='Видео URL'),
        ),
        migrations.AlterField(
            model_name='lessoncompletion',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='Education.enrollment', verbose_name='Зачисление'),
        ),
    ]
