# Generated by Django 5.2.7 on 2025-12-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0007_module_is_active_alter_lesson_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_url',
        ),
    ]
